# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='ammonia_range',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='last_ammonia',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='last_ph',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='last_temp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='light_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='ph_range',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='temp_range',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='last_water_change',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='water_change_freq',
            field=models.IntegerField(null=True),
        ),
    ]
