# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171102_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='ammonia_range',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='ph_range',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='temp_range',
        ),
        migrations.AddField(
            model_name='tank',
            name='ammonia_max',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tank',
            name='ammonia_min',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tank',
            name='ph_max',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tank',
            name='ph_min',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tank',
            name='temp_max',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tank',
            name='temp_min',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='tank',
            name='last_ph',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='tank',
            name='last_temp',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='tank',
            name='water_change_freq',
            field=models.IntegerField(default=0),
        ),
    ]
