# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171102_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_id', models.IntegerField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('temperature', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WaterChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_id', models.IntegerField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
