# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_temphistory_waterchangehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterchangehistory',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
