# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171103_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='last_temp',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tank',
            name='temp_max',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tank',
            name='temp_min',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
    ]
