# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171103_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_id', models.IntegerField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='tank',
            name='ammonia_max',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tank',
            name='ammonia_min',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tank',
            name='last_ammonia',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tank',
            name='last_ph',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tank',
            name='ph_max',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tank',
            name='ph_min',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='temphistory',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
