# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171103_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
