# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tank_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
