# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 06:19
from __future__ import unicode_literals

from django.db import migrations

def create_initial_tanks(apps, schema_editor):
    Tank = apps.get_model('tanks', 'Tank')

    Tank(name="Elliot's Tank", description="Small tank on the desk", water_change="2017-09-09").save()
    Tank(name="Boy Tank", description="Small tank in the middle", water_change="2017-09-09").save()
    Tank(name="Girl Tank", description="Medium tank on the right", water_change="2017-09-09").save()
    Tank(name="Big Tank", description="Large standalone tank", water_change="2017-09-09").save()

class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_tanks)
    ]
